In [1]:
from __future__ import print_function
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM
from keras.optimizers import RMSprop
from keras.utils.data_utils import get_file
import numpy as np
import random
import sys
from sklearn.cross_validation import train_test_split

Using TensorFlow backend.
/Users/akankshabindal/anaconda/envs/env/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [19]:
maxlen=40
languages = ['eng', 'frn', 'ger', 'czc','dns','dut','grk','hng','itn','jpn','lat','lit','ltn','ltn1','lux','mls','por'
             ,'rmn1','rum','rus','spn','ukr','yps']
text = []
for i,l in enumerate(languages):
    with open('subset/'+ l + '.txt','rt') as f:
        doc = f.read().lower()
    text.append(doc)
'''     
with open('subset1/eng.txt','rt') as f:
    text1 = f.read().lower()
with open('subset1/frn.txt','rt') as f:
    text2 = f.read().lower()
with open('subset/ger.txt','rt') as f:
    text3 = f.read().lower()
print('corpus length:', len(text1))
print('corpus length:', len(text2))
print('corpus length:', len(text3))
'''


"     \nwith open('subset1/eng.txt','rt') as f:\n    text1 = f.read().lower()\nwith open('subset1/frn.txt','rt') as f:\n    text2 = f.read().lower()\nwith open('subset/ger.txt','rt') as f:\n    text3 = f.read().lower()\nprint('corpus length:', len(text1))\nprint('corpus length:', len(text2))\nprint('corpus length:', len(text3))\n"

In [20]:
text1 = text[0]
text2 = text[1]
text3 = text[2]
text4 = text[3]
text5 = text[4]

text6 = text[5]
text7 = text[6]
text8 = text[7]
text9 = text[8]
text10 = text[9]
text11 = text[10]
text12 = text[11]
text13 = text[12]
text14 = text[13]
text15 = text[14]
text16 = text[15]
text17 = text[16]
text18 = text[17]
text19 = text[18]
text20 = text[19]
text21 = text[20]
text22 = text[21]
text23 = text[22]
chars = sorted(list(set(text[0] + text[1] +text[2] +text[3]+ text[4] + text[5] +text[6] + text[7]+ text[8] + text[9] 
                        +text[10] +text[11] + text[12] +text[13] +text[14] + text[15] +text[16] +text[17] + text[18] 
                        +text[19] +text[20] + text[21] + text[22])))
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

total chars: 131


In [21]:
#generating language model
def build_model(text, chars, char_indices):
    ##training set prepare
    maxlen= 40
    step = 1
    sentences_tr = []
    next_chars_tr = []
    for i in range(0, int(0.8*len(text)) - maxlen, step):
        sentences_tr.append(text[i: i + maxlen])
        next_chars_tr.append(text[i + maxlen])

    print('nb sequences:', len(sentences_tr))
    ##test set prepare
    sentences_test = []
    string_test= []
    step_test=20
    for i in range(int(0.8*len(text)) - maxlen,len(text) - maxlen, step_test):
        sentences_test.append(text[i: i + maxlen])
        string_test.append(text[i+maxlen:i+maxlen+5])
    print('nb sequences:', len(sentences_test))

    print('Vectorization...')
    X = np.zeros((len(sentences_tr), maxlen, len(chars)), dtype=np.bool)
    y = np.zeros((len(sentences_tr), len(chars)), dtype=np.bool)
    for i, sentence in enumerate(sentences_tr):
        for t, char in enumerate(sentence):
            X[i, t, char_indices[char]] = 1
        y[i, char_indices[next_chars_tr[i]]] = 1


    # build the model: a single LSTM
    print('Build model...')
    model = Sequential()
    model.add(LSTM(128, input_shape=(maxlen, len(chars))))
    model.add(Dense(len(chars)))
    model.add(Activation('softmax'))

    optimizer = RMSprop(lr=0.01)
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=["accuracy"])
    return X, y, sentences_test, string_test, model

In [22]:
languages = ['eng', 'frn', 'ger', 'czc','dns','dut','grk','hng','itn','jpn','lat','lit','ltn','ltn1','lux','mls','por'
             ,'rmn1','rum','rus','spn','ukr','yps']
X_eng, y_eng, sentences_eng_test, string_eng_test, model1 = build_model(text1, chars, char_indices) 
X_fr, y_fr, sentences_fr_test, string_fr_test, model2 = build_model(text2, chars, char_indices) 
X_ger, y_ger, sentences_ger_test, string_ger_test, model3 = build_model(text3, chars, char_indices) 
X_czc, y_czc, sentences_czc_test, string_czc_test, model4 = build_model(text4, chars, char_indices) 
X_dns, y_dns, sentences_dns_test, string_dns_test, model5 = build_model(text5, chars, char_indices) 
X_dut, y_dut, sentences_dut_test, string_dut_test, model6 = build_model(text6, chars, char_indices) 
X_grk, y_grk, sentences_grk_test, string_grk_test, model7 = build_model(text7, chars, char_indices) 

X_hng, y_hng, sentences_hng_test, string_hng_test, model8 = build_model(text8, chars, char_indices) 
X_itn, y_itn, sentences_itn_test, string_itn_test, model9 = build_model(text9, chars, char_indices) 
X_jpn, y_jpn, sentences_jpn_test, string_jpn_test, model10 = build_model(text10, chars, char_indices) 
X_lat, y_lat, sentences_lat_test, string_lat_test, model11 = build_model(text11, chars, char_indices) 
X_lit, y_lit, sentences_lit_test, string_lit_test, model12 = build_model(text12, chars, char_indices) 
X_ltn, y_ltn, sentences_ltn_test, string_ltn_test, model13 = build_model(text13, chars, char_indices) 
X_ltn1, y_ltn1, sentences_ltn1_test, string_ltn1_test, model14 = build_model(text14, chars, char_indices)


nb sequences: 8556
nb sequences: 108
Vectorization...
Build model...
nb sequences: 9857
nb sequences: 124
Vectorization...
Build model...
nb sequences: 9760
nb sequences: 123
Vectorization...
Build model...
nb sequences: 8936
nb sequences: 113
Vectorization...
Build model...
nb sequences: 9850
nb sequences: 124
Vectorization...
Build model...
nb sequences: 10270
nb sequences: 129
Vectorization...
Build model...
nb sequences: 18195
nb sequences: 228
Vectorization...
Build model...
nb sequences: 10589
nb sequences: 133
Vectorization...
Build model...
nb sequences: 10244
nb sequences: 129
Vectorization...
Build model...
nb sequences: 9935
nb sequences: 125
Vectorization...
Build model...
nb sequences: 10852
nb sequences: 137
Vectorization...
Build model...
nb sequences: 8808
nb sequences: 111
Vectorization...
Build model...
nb sequences: 8012
nb sequences: 101
Vectorization...
Build model...
nb sequences: 8056
nb sequences: 102
Vectorization...
Build model...


In [23]:
X_lux, y_lux, sentences_lux_test, string_lux_test, model15 = build_model(text15, chars, char_indices) 
X_mls, y_mls, sentences_mls_test, string_mls_test, model16 = build_model(text16, chars, char_indices) 
X_por, y_por, sentences_por_test, string_por_test, model17 = build_model(text17, chars, char_indices) 
X_rmn1, y_rmn1, sentences_rmn1_test, string_rmn1_test, model18 = build_model(text18, chars, char_indices) 
X_rum, y_rum, sentences_rum_test, string_rum_test, model19 = build_model(text19, chars, char_indices) 
X_rus, y_rus, sentences_rus_test, string_rus_test, model20 = build_model(text20, chars, char_indices) 
X_spn, y_spn, sentences_spn_test, string_spn_test, model21 = build_model(text21, chars, char_indices)

X_ukr, y_ukr, sentences_ukr_test, string_ukr_test, model22 = build_model(text22, chars, char_indices) 
X_yps, y_yps, sentences_yps_test, string_yps_test, model23 = build_model(text23, chars, char_indices)

nb sequences: 10244
nb sequences: 129
Vectorization...
Build model...
nb sequences: 9359
nb sequences: 118
Vectorization...
Build model...
nb sequences: 9444
nb sequences: 119
Vectorization...
Build model...
nb sequences: 9194
nb sequences: 116
Vectorization...
Build model...
nb sequences: 10176
nb sequences: 128
Vectorization...
Build model...
nb sequences: 17442
nb sequences: 219
Vectorization...
Build model...
nb sequences: 9788
nb sequences: 123
Vectorization...
Build model...
nb sequences: 16456
nb sequences: 207
Vectorization...
Build model...
nb sequences: 8850
nb sequences: 112
Vectorization...
Build model...


In [24]:
def vectorize(sentence, chars , char_indices ):
    X = np.zeros((1, maxlen, len(chars)), dtype=np.bool)
    for t, char in enumerate(sentence):
        X[0, t, char_indices[char]] = 1
    return X

In [25]:
def get_scores_for_model(seed,next_string, model,chars,char_indices):
    sentence =seed
    prob_char=0.0
    x = np.zeros((5, maxlen, len(chars)))

    x[0] = vectorize(seed,chars,char_indices)
    x[1] = vectorize(seed[1:]+next_string[:1],chars,char_indices)
    x[2] = vectorize(seed[2:]+next_string[:2],chars,char_indices)
    x[3] = vectorize(seed[3:]+next_string[:3],chars,char_indices)
    x[4] = vectorize(seed[4:]+next_string[:4],chars,char_indices)
    probs_term = []
    for i in range(5):
        preds = model.predict(x[i].reshape(1,40,131), verbose=0)[0]
        preds = np.log(preds)
        probs_term.append(preds[char_indices[next_string[i]]])

    return probs_term
        

In [26]:
#Create a test SET of all language sentences
languages = ['eng', 'frn', 'ger', 'czc','dns','dut','grk','hng','itn','jpn','lat','lit','ltn','ltn1','lux','mls','por'
             ,'rmn1','rum','rus','spn','ukr','yps']
sentences_test=[]
string_test=[]
test_size = 10
sentences_test.append(sentences_fr_test[:test_size])
string_test.append(string_fr_test[:test_size])

sentences_test.append(sentences_eng_test[:test_size])
string_test.append(string_eng_test[:test_size])

sentences_test.append(sentences_ger_test[:test_size])
string_test.append(string_ger_test[:test_size])

sentences_test.append(sentences_czc_test[:test_size])
string_test.append(string_czc_test[:test_size])

sentences_test.append(sentences_dns_test[:test_size])
string_test.append(string_dns_test[:test_size])

sentences_test.append(sentences_dut_test[:test_size])
string_test.append(string_dut_test[:test_size])

sentences_test.append(sentences_grk_test[:test_size])
string_test.append(string_grk_test[:test_size])

sentences_test.append(sentences_hng_test[:test_size])
string_test.append(string_hng_test[:test_size])

sentences_test.append(sentences_itn_test[:test_size])
string_test.append(string_itn_test[:test_size])

sentences_test.append(sentences_jpn_test[:test_size])
string_test.append(string_jpn_test[:test_size])

sentences_test.append(sentences_lat_test[:test_size])
string_test.append(string_lat_test[:test_size])

sentences_test.append(sentences_lit_test[:test_size])
string_test.append(string_lit_test[:test_size])
languages = ['eng', 'frn', 'ger', 'czc','dns','dut','grk','hng','itn','jpn','lat','lit','ltn','ltn1','lux','mls','por'
             ,'rmn1','rum','rus','spn','ukr','yps']
sentences_test.append(sentences_ltn_test[:test_size])
string_test.append(string_ltn_test[:test_size])

sentences_test.append(sentences_ltn1_test[:test_size])
string_test.append(string_ltn1_test[:test_size])

sentences_test.append(sentences_lux_test[:test_size])
string_test.append(string_lux_test[:test_size])

sentences_test.append(sentences_mls_test[:test_size])
string_test.append(string_mls_test[:test_size])

sentences_test.append(sentences_por_test[:test_size])
string_test.append(string_por_test[:test_size])

sentences_test.append(sentences_rmn1_test[:test_size])
string_test.append(string_rmn1_test[:test_size])

sentences_test.append(sentences_rum_test[:test_size])
string_test.append(string_rum_test[:test_size])

sentences_test.append(sentences_rus_test[:test_size])
string_test.append(string_rus_test[:test_size])

sentences_test.append(sentences_spn_test[:test_size])
string_test.append(string_spn_test[:test_size])

sentences_test.append(sentences_ukr_test[:test_size])
string_test.append(string_ukr_test[:test_size])

sentences_test.append(sentences_yps_test[:test_size])
string_test.append(string_yps_test[:test_size])
import csv
with open("test_all.csv", 'wt') as f:
    w = csv.writer(f, dialect='excel')
    for row in string_test:
        w.writerow(row)
print(len(sentences_test))


23


In [27]:
def save_model(model, prob, language):
    model_json = model.to_json()
    with open("model/model_"+language+".json", "w") as json_file:
        json_file.write(model_json)
    # serialize weights to HDF5
    model.save_weights("weights/model_"+ language + ".h5")
    print("Saved model to disk")
    
    with open("prob/output_prob_" + language + ".csv", 'wt') as f:
        w = csv.writer(f, dialect='excel')
        for row in prob:
            w.writerow(row)

In [28]:
import csv
# train the model, output generated text after each iteration
def train_model(model, X, y, sentences_all_test, string_all_test , chars, char_indices):
    print()
    #print('-' * 50)
    #print('Iteration', iteration)
    a=model.fit(X, y,
              batch_size=128,
              epochs=20, verbose = 0)
    #model_eng_json = model.to_json()
    #with open("model/model_eng_"+str(iteration)+".json", "w") as json_file:
    #    json_file.write(model_eng_json)
    # serialize weights to HDF5
    #model.save_weights("weights/model_eng_"+ str(iteration) +".h5")
    #print("Saved model to disk")

    #sentence=
    prob = []
    for idx in range(len(sentences_all_test)):
        sentences_test = sentences_all_test[idx]
        string_test = string_all_test[idx]
        for i in range(len(sentences_test)):
            prob.append(get_scores_for_model(sentences_test[i], string_test[i], model,chars, char_indices))
    return model, prob

In [110]:
model1, prob_eng = train_model(model1, X_eng, y_eng, sentences_test, string_test, chars, char_indices)
save_model(model1, prob_eng, 'eng')

/Users/akankshabindal/anaconda/envs/env/lib/python2.7/site-packages/ipykernel/__main__.py:14: RuntimeWarning: divide by zero encountered in log


Saved model to disk


In [29]:
model2, prob_fr = train_model(model2, X_fr, y_fr, sentences_test, string_test, chars, char_indices)
save_model(model2, prob_fr, 'fr')

/Users/akankshabindal/anaconda/envs/env/lib/python2.7/site-packages/ipykernel/__main__.py:14: RuntimeWarning: divide by zero encountered in log


Saved model to disk


IOError: [Errno 2] No such file or directory: 'prob/output_prob_fr.csv'

In [112]:
model3, prob_ger = train_model(model3, X_ger, y_ger, sentences_test, string_test, chars, char_indices)
save_model(model3, prob_ger, 'ger')
model4, prob_czc = train_model(model4, X_czc, y_czc, sentences_test, string_test, chars, char_indices)
save_model(model4, prob_czc, 'czc')
model5, prob_dns = train_model(model5, X_dns, y_dns, sentences_test, string_test, chars, char_indices)
save_model(model5, prob_dns, 'dns')
model6, prob_dut = train_model(model6, X_dut, y_dut, sentences_test, string_test, chars, char_indices)
save_model(model6, prob_dut, 'dut')
model7, prob_grk = train_model(model7, X_grk, y_grk, sentences_test, string_test, chars, char_indices)
save_model(model7, prob_grk, 'grk')
model8, prob_hng = train_model(model8, X_hng, y_hng, sentences_test, string_test, chars, char_indices)
save_model(model8, prob_hng, 'hng')

model9, prob_itn = train_model(model9, X_itn, y_itn, sentences_test, string_test, chars, char_indices)
save_model(model9, prob_itn, 'itn')
model10, prob_jpn = train_model(model10, X_jpn, y_jpn, sentences_test, string_test, chars, char_indices)
save_model(model10, prob_jpn, 'jpn')
model11, prob_lat = train_model(model11, X_lat, y_lat, sentences_test, string_test, chars, char_indices)
save_model(model11, prob_lat, 'lat')
model12, prob_lit = train_model(model12, X_lit, y_lit, sentences_test, string_test, chars, char_indices)
save_model(model12, prob_lit, 'lit')
model13, prob_ltn = train_model(model13, X_ltn, y_ltn, sentences_test, string_test, chars, char_indices)
save_model(model13, prob_ltn, 'ltn')
model14, prob_ltn1 = train_model(model14, X_ltn1, y_ltn1, sentences_test, string_test, chars, char_indices)
save_model(model14, prob_ltn1, 'ltn1')
languages = ['eng', 'frn', 'ger', 'czc','dns','dut','grk','hng','itn','jpn','lat','lit','ltn','ltn1','lux','mls','por'
             ,'rmn1','rum','rus','spn','ukr','yps']
model15, prob_lux = train_model(model15, X_lux, y_lux, sentences_test, string_test, chars, char_indices)
save_model(model15, prob_lux, 'lux')
model16, prob_mls = train_model(model16, X_mls, y_mls, sentences_test, string_test, chars, char_indices)
save_model(model16, prob_mls, 'mls')
model17, prob_por = train_model(model17, X_por, y_por, sentences_test, string_test, chars, char_indices)
save_model(model17, prob_por, 'por')
model18, prob_rmn1 = train_model(model18, X_rmn1, y_rmn1, sentences_test, string_test, chars, char_indices)
save_model(model18, prob_rmn1, 'rmn1')

model19, prob_rum = train_model(model19, X_rum, y_rum, sentences_test, string_test, chars, char_indices)
save_model(model19, prob_rum, 'rum')
model20, prob_rus = train_model(model20, X_rus, y_rus, sentences_test, string_test, chars, char_indices)
save_model(model20, prob_rus, 'rus')
model21, prob_spn = train_model(model21, X_spn, y_spn, sentences_test, string_test, chars, char_indices)
save_model(model21, prob_spn, 'spn')
model22, prob_ukr = train_model(model22, X_ukr, y_ukr, sentences_test, string_test, chars, char_indices)
save_model(model22, prob_ukr, 'ukr')
model23, prob_yps = train_model(model23, X_yps, y_yps, sentences_test, string_test, chars, char_indices)
save_model(model23, prob_yps, 'yps')


Saved model to disk

Saved model to disk



/Users/akankshabindal/anaconda/envs/env/lib/python2.7/site-packages/ipykernel/__main__.py:14: RuntimeWarning: divide by zero encountered in log


Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk

Saved model to disk


In [141]:
def predict_language(prob_eng, prob_fr, prob_ger, prob_czc, prob_dns, prob_dut, prob_grk, prob_hng, prob_itn,
                    prob_jpn, prob_lat, prob_lit, prob_ltn, prob_ltn1, prob_lux, prob_mls, prob_por,
                    prob_rmn1, prob_rum, prob_rus, prob_spn, prob_ukr, prob_yps):
    y = [0] * len(prob_eng)
    probs_eng = []
    probs_frn = []
    probs_ger = []
    for i in range(len(prob_eng)):
        sum_eng= sum_fr= sum_ger= sum_czc= sum_dns= sum_dut= sum_grk= sum_hng= sum_itn=sum_jpn= sum_lat= sum_lit= sum_ltn= sum_ltn1= sum_lux= sum_mls= sum_por= sum_rmn1=sum_rum= sum_rus= sum_spn= sum_ukr= sum_yps = 0
        for j in range(len(prob_eng[0])):
            sum_eng += float(prob_eng[i][j])
            sum_fr += float(prob_fr[i][j])
            sum_ger += float(prob_ger[i][j])
            sum_czc += float(prob_czc[i][j])
            sum_dns += float(prob_dns[i][j])
            sum_dut += float(prob_dut[i][j])
            sum_grk += float(prob_grk[i][j])

            sum_hng += float(prob_hng[i][j])
            sum_itn += float(prob_itn[i][j])
            sum_jpn += float(prob_jpn[i][j])
            sum_lat += float(prob_lat[i][j])
            sum_lit += float(prob_lit[i][j])
            sum_ltn += float(prob_ltn[i][j])

            sum_ltn1 += float(prob_ltn1[i][j])
            sum_lux += float(prob_lux[i][j])
            sum_por += float(prob_por[i][j])
            sum_rmn1 += float(prob_rmn1[i][j])
            sum_rum += float(prob_rum[i][j])
            sum_rus += float(prob_rus[i][j])

            sum_spn += float(prob_spn[i][j])
            sum_ukr += float(prob_ukr[i][j])
            sum_yps += float(prob_yps[i][j])

        sum_eng = np.exp(sum_eng)
        sum_fr = np.exp(sum_fr)
        sum_ger = np.exp(sum_ger)
        sum_czc = np.exp(sum_czc)
        sum_dns = np.exp(sum_dns)
        sum_dut = np.exp(sum_dut)
        sum_grk = np.exp(sum_grk)
        sum_hng = np.exp(sum_hng)
        sum_itn = np.exp(sum_itn)
        sum_jpn = np.exp(sum_jpn)
        sum_lat = np.exp(sum_lat)
        sum_lit = np.exp(sum_lit)

        sum_ltn = np.exp(sum_ltn)
        sum_ltn1 = np.exp(sum_ltn1)
        sum_lux = np.exp(sum_lux)
        sum_por = np.exp(sum_por)
        sum_rmn1 = np.exp(sum_rmn1)
        sum_rum = np.exp(sum_rum)
        sum_rus = np.exp(sum_rus)
        sum_spn = np.exp(sum_spn)
        sum_ukr = np.exp(sum_ukr)
        sum_yps = np.exp(sum_yps)
        sum_total = np.array([sum_eng, sum_fr, sum_ger, sum_czc, sum_dns, sum_dut, sum_grk, sum_hng, sum_itn,
                    sum_jpn, sum_lat, sum_lit, sum_ltn, sum_ltn1, sum_lux, sum_mls, sum_por, sum_rmn1,
                    sum_rum, sum_rus, sum_spn, sum_ukr, sum_yps])
        #print(sum_total)
        max_idx = np.argmax(sum_total)
        y[i] = max_idx
        #if sum_fr == 0.0:
            #sum_fr = 0.0000000001
            #print(str(i) + "Zero")
        probs_eng.append(sum_eng)
        probs_frn.append(sum_fr)
        probs_ger.append(sum_ger)
    return y, probs_eng, probs_frn

In [142]:
b= e =1
c =2
d =-1
a = np.array([b, c , d])
print(a.shape)
m = np.argmax(a)
print(i,m)

(3,)
22 1


In [144]:
import matplotlib.pyplot as plt

with open("prob/output_prob_" + 'eng' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_eng = list(w)
with open("prob/output_prob_" + 'fr' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_fr = list(w)
with open("prob/output_prob_" + 'ger' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_ger = list(w)
with open("prob/output_prob_" + 'czc' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_czc = list(w)
with open("prob/output_prob_" + 'dns' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_dns = list(w)
with open("prob/output_prob_" + 'dut' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_dut = list(w)
with open("prob/output_prob_" + 'grk' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_grk = list(w)
with open("prob/output_prob_" + 'hng' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_hng = list(w)
with open("prob/output_prob_" + 'itn' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_itn = list(w)
with open("prob/output_prob_" + 'jpn' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_jpn = list(w)
with open("prob/output_prob_" + 'lat' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_lat = list(w)
with open("prob/output_prob_" + 'lit' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_lit = list(w)
with open("prob/output_prob_" + 'ltn' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_ltn = list(w)
with open("prob/output_prob_" + 'ltn1' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_ltn1 = list(w)
with open("prob/output_prob_" + 'lux' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_lux = list(w)
with open("prob/output_prob_" + 'mls' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_mls = list(w)
with open("prob/output_prob_" + 'por' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_por = list(w)
with open("prob/output_prob_" + 'rmn1' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_rmn1 = list(w)
with open("prob/output_prob_" + 'rum' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_rum = list(w)
with open("prob/output_prob_" + 'rus' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_rus = list(w)
with open("prob/output_prob_" + 'spn' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_spn = list(w)
with open("prob/output_prob_" + 'ukr' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_ukr = list(w)
with open("prob/output_prob_" + 'yps' + ".csv", 'rt') as f:
        w = csv.reader(f, delimiter=',')
        prob_yps = list(w)
#print((prob_english), len(prob_fr))
#true_labels = ([0] * 230)# + ([1] * 220)
true_labels=[]
for i in range(23):
    true_labels+=[i]*10
#print(true_labels.shape)

from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score, auc, roc_curve
#try:
pred_y, logprob_english, logprob_fr = predict_language(prob_eng, prob_fr, prob_ger, prob_czc, prob_dns, prob_dut, 
                                                       prob_grk, prob_hng, prob_itn,
                    prob_jpn, prob_lat, prob_lit, prob_ltn, prob_ltn1, prob_lux, prob_mls, prob_por,
                    prob_rmn1, prob_rum, prob_rus, prob_spn, prob_ukr, prob_yps)
#except:
#    continue
#x = [e for i, e in enumerate(logprob_fr) if e == 0]
#print(x)
print(min(logprob_fr), max(logprob_fr))
y_hat = np.array([a/b for (a, b) in zip(logprob_english, logprob_fr)])
#roc_auc_score(true_labels, y_hat)

#print(pred_y)
print (confusion_matrix(true_labels, pred_y))
print (accuracy_score(true_labels, pred_y))
#print (y_hat)
try:
    fpr, tpr, _ = roc_curve(true_labels, y_hat)
    roc_auc = auc(fpr, tpr)
    plt.figure()
    lw = 2
    plt.plot(fpr, tpr, color='darkorange',
             lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
    plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic example')
    plt.legend(loc="lower right")
    plt.show()
except:
    print("Error")

8.31740494607e-57 0.89722283182
[[ 0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0  0]
 [ 3  0  0  0  2  0  0  0  0  0  0  0  0  2  0  0  0  0  1  0  0  2  0]
 [ 0  0  5  1  1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  2  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  2  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  5  0  1  0  0  0  0  0  0  1  0  0  1  0  0  1  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  1  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  9  0  0  1  0  0  0  0  0  0  0  0]
 [ 1  1  0  0  0  0  0  0  0  0  0  0  4  1  0  0  2  0  1  0  0  0  0]
 [ 0  0  1  0  1  0  0  0  0  0 

In [ ]:
languages = ['eng', 'frn', 'ger', 'czc','dns','dut','grk','hng','itn','jpn','lat','lit','ltn','ltn1','lux','mls','por'
             ,'rmn1','rum','rus','spn','ukr','yps']